name: Test Arturo's Installation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: echo "PATH=$HOME/.arturo/bin:$PATH" >> $GITHUB_ENV

      - name: Make install.sh executable
        if: runner.os != 'Windows'
        run: chmod +x ./install.sh

      - name: Install Arturo (DOS)
        if: matrix.os == 'windows-latest'
        run: ./install.ps1
    
      - name: Install Arturo (UNIX)
        if: matrix.os != 'windows-latest'
        run: ./install.sh

      - name: Test Arturo
        run: arturo hello.art
